name: plaster 0f paris
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9216728287283331
  lightness: 0.7072880086489022
  saturation: 0.30019190232269466
  rhythmicContrast: 0.49886608263477683
purpose: []
